import {BerthName} from "../../../types";

/**
 * 2-character alphanumeric code representing the train describer (area) that sent a message.
 *
 * @see {@link https://wiki.openraildata.com/index.php/List_of_Train_Describers}
 */
export type TrainDescriberId = string;

/** Type of message received from a train describer related to berth movements. */
export type BerthMsgType = 'BERTH STEP' | 'BERTH CANCEL' | 'BERTH INTERPOSE';

/** Type of message received from a train describer related to signalling updates. */
export type SignallingMsgType = 'SIGNALLING UPDATE' | 'SIGNALLING REFRESH' | 'SIGNALLING REFRESH FINISHED';

/** Type of message received from a train describer. */
export type TrainDescriberMsgType = BerthMsgType | SignallingMsgType | 'HEARTBEAT';

/** Base structure for all messages from a train describer. */
export interface BaseTrainDescriberMsg {
  msgType: TrainDescriberMsgType;
  /** When the message was generated by the train describer. */
  time: Date
  /** The train describer that sent this message. */
  areaId: TrainDescriberId;
}

/** Base structure for messages from a train describer related to berth movements. */
interface BerthMsgBase extends BaseTrainDescriberMsg {
  msgType: BerthMsgType;
}

/** Message from a train describer indicating a train moving from one berth to another. */
export interface BerthStepMsg extends BerthMsgBase {
  msgType: 'BERTH STEP';
  /** Description (usually a headcode) being moved. */
  description: string;
  /** The berth the description is moving from. */
  from: BerthName;
  /** The berth the description is moving to. */
  to: BerthName;
}

/** Message from a train describer indicating a train cancelling from a berth. */
export interface BerthCancelMsg extends BerthMsgBase {
  msgType: 'BERTH CANCEL';
  /** Description (usually a headcode) being cancelled. */
  description: string;
  /** The berth the description is cancelling from. */
  from: BerthName;
}

/** Message from a train describer indicating a train interposing into a berth. */
export interface BerthInterposeMsg extends BerthMsgBase {
  msgType: 'BERTH INTERPOSE';
  /** Description (usually a headcode) being interposed. */
  description: string;
  /** The berth the train is interposing into. */
  to: BerthName;
}

/** Heartbeat message from a train describer. */
export interface HeartbeatMsg extends BaseTrainDescriberMsg {
  msgType: 'HEARTBEAT';
  /** When the train describer sent this heartbeat message. Only precise to the minute. */
  reportTime: Date
}

/**
 * Base structure for messages from a train describer related to signalling updates.
 *
 * The meaning of this data varies a lot between train describers, and isn't fully documented yet,
 *  so unfortunately you will have to parse it yourself!
 *
 * @see {@link https://wiki.openraildata.com/index.php/S_Class_Messages}
 */
interface SignallingMsgBase extends BaseTrainDescriberMsg {
  msgType: SignallingMsgType;
  /** Address of the signalling data being updated */
  address: string;
  /** Signalling data (hex bitmap) */
  data: string;
}

/** SF (Signalling update) message from a train describer. Individual element change. */
export interface SignallingUpdateMsg extends SignallingMsgBase {
  msgType: 'SIGNALLING UPDATE';
}

/** SG (Signalling refresh) message from a train describer. Batch update payload. */
export interface SignallingRefreshMsg extends SignallingMsgBase {
  msgType: 'SIGNALLING REFRESH';
}

/** SH (Signalling refresh finished) message from a train describer. Terminator for a batch of SG messages. */
export interface SignallingRefreshFinishedMsg extends SignallingMsgBase {
  msgType: 'SIGNALLING REFRESH FINISHED';
}

/** Message received from a train describer related to berth movements. */
export type BerthMsg = BerthStepMsg | BerthCancelMsg | BerthInterposeMsg;

/** Message received from a train describer related to signalling updates. */
export type SignallingMsg = SignallingUpdateMsg | SignallingRefreshMsg | SignallingRefreshFinishedMsg;

/** Message received from a train describer. */
export type TrainDescriberMsg = BerthMsg | SignallingMsg | HeartbeatMsg;
