import {BerthName, UnixEpochMsTimestamp} from "../../../types";

/**
 * 2-character alphanumeric code representing the train describer (area) that sent a message.
 *
 * @see {@link https://wiki.openraildata.com/index.php/List_of_Train_Describers}
 */
export type TrainDescriberId = string;

/**
 * Type of C-Class (Berth) message.
 *
 * @see {@link https://wiki.openraildata.com/index.php/C_Class_Messages}
 */
export type CClassMsgType = 'CA' | 'CB' | 'CC' | 'CT';

/**
 * Type of S-Class (Signalling) message.
 *
 * @see {@link https://wiki.openraildata.com/index.php/S_Class_Messages}
 */
export type SClassMsgType = 'SF' | 'SG' | 'SH';

/**
 * Type of message received from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/TD#Message_types}
 */
export type TrainDescriberMsgType = CClassMsgType | SClassMsgType;

/** Base structure for all messages from a train describer. */
interface BaseTrainDescriberMsg {
  msg_type: TrainDescriberMsgType;
  /**
   * When the message was generated by the train describer.
   *
   * Note that, due to a known bug in the feed, timestamps may be off by 24 hours
   *  for events that occur very briefly before midnight.
   *
   * @see {@link https://wiki.openraildata.com/index.php/TD#Cross-midnight_bug}
   */
  time: UnixEpochMsTimestamp
  /** The train describer that sent this message. */
  area_id: TrainDescriberId;
}

/**
 * Base structure for C-Class (Berth) messages from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/C_Class_Messages}
 */
interface CClassMsgBase extends BaseTrainDescriberMsg {
  msg_type: CClassMsgType;
}

/** CA (Berth step) message from a train describer. Moves description from one berth to another. */
export interface CaMsg extends CClassMsgBase {
  msg_type: 'CA';
  /** Description (usually a headcode) of the train or movement. */
  descr: string;
  /** The berth the train is moving from. */
  from: BerthName;
  /** The berth the train is moving to. */
  to: BerthName;
}

/** CB (Berth cancel) message from a train describer. Cancels description in a berth. */
export interface CbMsg extends CClassMsgBase {
  msg_type: 'CB';
  /** Description (usually a headcode) being cancelled. */
  descr: string;
  /** The berth the train is cancelling from. */
  from: BerthName;
}

/** CC (Berth interpose) message from a train describer. Inserts description into a berth. */
export interface CcMsg extends CClassMsgBase {
  msg_type: 'CC';
  /** Description (usually a headcode) being interposed. */
  descr: string;
  /** The berth the description is interposing into. */
  to: BerthName;
}

/** CT (Heartbeat) message from a train describer. Periodically sent from a train describer. */
export interface CtMsg extends CClassMsgBase {
  msg_type: 'CT';
  /** When the train describer sent this heartbeat message in HHMM format. */
  report_time: string;
}

/**
 * Base structure for S-Class (Signalling) messages from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/S_Class_Messages}
 */
interface SClassMsgBase extends BaseTrainDescriberMsg {
  msg_type: SClassMsgType;
  /** Hex address of the signalling data being updated */
  address: string;
  /** Signalling data (hex bitmap) */
  data: string;
}

/** SF (Signalling update) message from a train describer. Individual element change. */
export interface SfMsg extends SClassMsgBase {
  msg_type: 'SF';
}

/** SG (Signalling refresh) message from a train describer. Batch update payload. */
export interface SgMsg extends SClassMsgBase {
  msg_type: 'SG';
}

/** SH (Signalling refresh finished) message from a train describer. Terminator for a batch of SG messages. */
export interface ShMsg extends SClassMsgBase {
  msg_type: 'SH';
}

/**
 * C-Class (Berth) message received from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/C_Class_Messages}
 */
export type CClassMsg = CaMsg | CbMsg | CcMsg | CtMsg;

/**
 * S-Class (Signalling) message received from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/S_Class_Messages}
 */
export type SClassMsg = SfMsg | SgMsg | ShMsg;

/**
 * Message received from a train describer.
 *
 * @see {@link https://wiki.openraildata.com/index.php/TD#Message_types}
 */
export type TrainDescriberMsg = CClassMsg | SClassMsg;

/** Wrapped message received from the Train Describer feed, where the top-level key corresponds to the message type. */
export type TrainDescriberMsgWrapper<T extends TrainDescriberMsgType = TrainDescriberMsgType> =
    T extends any ? {
      [K in `${T}_MSG`]: Extract<TrainDescriberMsg, { msg_type: T }>
    } : never;
