import {BerthName, UnixEpochMsTimestamp} from "../../../types";

/**
 * 2-character alphanumeric code representing the train describer that sent a message
 *
 * @see {@link https://wiki.openraildata.com/index.php/List_of_Train_Describers}
 */
export type TrainDescriberId = string;

/**
 * C-Class (Berth) messages
 * https://wiki.openraildata.com/index.php/C_Class_Messages
 */
export type CClassMsgType = 'CA' | 'CB' | 'CC' | 'CT';

/**
 * S-Class (Signalling) messages
 * https://wiki.openraildata.com/index.php/S_Class_Messages
 */
export type SClassMsgType = 'SF' | 'SG' | 'SH';

/** A type of message received from the train describer feed */
export type TrainDescriberMsgType = CClassMsgType | SClassMsgType;

/** Base structure for all messages from the train describer feed */
interface BaseTrainDescriberMsg {
  msg_type: TrainDescriberMsgType;
  /** The time the message was generated by the train describer */
  time: Date
  /** The train describer that sent this message */
  area_id: TrainDescriberId;
}

export interface CClassMsgBase extends BaseTrainDescriberMsg {
  msg_type: CClassMsgType;
  /** Description of the train or movement */
  descr: string;
}

/** Berth Step: Moves description from one berth to another */
export interface CaMsg extends CClassMsgBase {
  msg_type: 'CA';
  /** The berth the train is moving from */
  from: BerthName;
  /** The berth the train is moving to */
  to: BerthName;
}

/** Berth Cancel: Cancels description in the 'from' berth */
export interface CbMsg extends CClassMsgBase {
  msg_type: 'CB';
  /** The berth the train is cancelling from */
  from: BerthName;
  /** Description of the train or cancellation */
  descr: string;
}

/** Berth Interpose: Inserts description into the 'to' berth */
export interface CcMsg extends CClassMsgBase {
  msg_type: 'CC';
  /** The berth the train is interposing into */
  to: BerthName;
  /** Description of the train or interposition */
  descr: string;
}

/** Heartbeat: Periodically sent from a train describer */
export interface CtMsg extends CClassMsgBase {
  msg_type: 'CT';
  /** The time the train describer sent this heartbeat message in HHMM format. */
  report_time: string;
}

interface SClassMsgBase extends BaseTrainDescriberMsg {
  msg_type: SClassMsgType;
  /** Hex address of the signalling data being updated */
  address: string;
  /**
   * Signalling data (hex bitmap)
   * https://wiki.openraildata.com/index.php/Decoding_S-Class_Data
   */
  data: string;
}

/** Signalling Update (Individual element change) */
export interface SfMsg extends SClassMsgBase {
  msg_type: 'SF';
}

/** Signalling Refresh (Batch update payload) */
export interface SgMsg extends SClassMsgBase {
  msg_type: 'SG';
}

/** Signalling Refresh Finished (Terminator for SG messages) */
export interface ShMsg extends SClassMsgBase {
  msg_type: 'SH';
}

/** A message received from a train describer related to berth movements */
export type CClassMsg = CaMsg | CbMsg | CcMsg | CtMsg;

/** A message received from a train describer related to signalling updates */
export type SClassMsg = SfMsg | SgMsg | ShMsg;

/** A message received from a train describer and parsed */
export type TrainDescriberMsg = CClassMsg | SClassMsg;

/** Utility type to apply `Omit` distributively over unions */
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/** The raw message format received from the train describer feed before parsing */
export type RawTrainDescriberMsg = DistributiveOmit<TrainDescriberMsg, 'time'> & { time: UnixEpochMsTimestamp };
